apiVersion: batch/v1
kind: Job
metadata:
  name: named-dataset-stt
  namespace: panoptes
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      imagePullSecrets:
      - name: panoptes-registry-credentials
      containers:
      - name: named-dataset
        image: registry.docker.nat.bt.com/panoptes/feast-repo:latest
        command: ["python", "/feast/scripts/createNamedDatasetSTT.py"]
      restartPolicy: Never
  backoffLimit: 2